### ISSUE TITLE
VSCode debug with @einsum stops in macro.jl 

### ISSUE THREAD

**Issue by rd-conti** [mcabbott/Tullio.jl#33] opened 2020-09-09 15:09 UTC
Dear Michael, 

I'm using `@einsum` from Tullio and I get an unexpected behavior when debugging a julia program in VSCode, https://www.julia-vscode.org/. The debugger always stops at the same line in macro.jl.  
Say, I have a program like 

    using Tullio: @einsum

    v = [1; 2; 3];
    w = [4; 5; 6];       # <== 1st breakpoint
    @einsum a[i,j] := v[i] * w[j]; 
    println("a=", a); 
    b  = 4 * a;          # <== 2nd breakpoint 
    println("b=", b);

After I start the debugger with `F5` VSCode shows correct behavior at the 1st breakpoint, see the attached file  `2_debugger_at_1st_BP.PNG`. When I continue with `F5` the debugger stops in line 826 of `macro.jl`. See attached file `3_debugger_stops_in_macro_jl.PNG`. Another continue with `F5` leads me to the 2nd BP, see file `4_debugger_at_2n_BP.PNG`.

In case I have several `@einsum` statements the debugger stops several times always in `macro.jl` at line 826. That can be disturbing if I want to debug code after many `@einsum` statements. 

This behavior may be also related to VSCode but maybe you have a hint? 

Thank you 

Ralf

After starting the debugger with `F5` at the 1st breakpoint (as expected)

![2_debugger_at_1st_BP](https://user-images.githubusercontent.com/70198296/92612791-822c4680-f2ba-11ea-952f-a03859398245.PNG)

Continue `F5` and the debugger stops in `macro.jl` (unexpected behavior)

![3_debugger_stops_in_macro_jl](https://user-images.githubusercontent.com/70198296/92612387-1ea21900-f2ba-11ea-8e47-eae966a2077d.PNG)

Another Continue `F5` and the debugger stops at the 2nd break point (as expected)

![4_debugger_at_2nd_BP](https://user-images.githubusercontent.com/70198296/92612405-2366cd00-f2ba-11ea-85c4-0e7198be5968.PNG)

**Comment by mcabbott** [comment] 2020-09-11 10:46
Hi Ralf, thanks for the detailed report! I finally got vscode to co-operate, and can reproduce this. 

It's pretty odd, but I don't understand why the macro's `let` block ought to cause problems. If I define a function `f(v,w) = @einsum a[i,j] := v[i] * w[j];` and then call that on line 5, it still stops in the same place; perhaps that means it isn't some weird global scope issue.

**Comment by rd-conti** [comment] 2020-09-12 06:54
Hi Michael, thank you for your efforts. 

Now, strange thing: 
I installed the package `Debugger`, https://github.com/JuliaDebug/Debugger.jl, a command line debugger to check if it fails too.
But after installing this package, which is not needed by Julia VSCode, the unexpected behavior of stopping in `macro.jl` disappears while debugging in VSCode.
Remove this package with `rm Debugger` and the unexpected behavior in VSCode appears again.  I don't know if VSCode debugger has it's own Debugger or JuliaInterpreter or? 
Could you imagine, if your time permits, a small macro example which would trigger this behavior of VSCode debugger. Then we could report this to https://github.com/julia-vscode/julia-vscode. In case it is not so simple and takes too much effort, we could also report the current behaviour to julia-vscode. 

Cheers 

Ralf

**Comment by mcabbott** [comment] 2020-09-14 13:28
I still get the same behaviour after installing (and loading) Debugger. I also don't know the relation between it and the one used by VSCode, they may share some innards.

I think best to open an issue on VSCode, and see what they say. It seems straightforward to reproduce at least the basic version of this, with a registered package. `Base.remove_linenums!(@macroexpand1 @einsum a[i,j] := v[i] * w[j])` is not impossibly long to read. Maybe the fix will be obvious to someone there...

**Comment by rd-conti** [comment] 2020-09-15 18:19
> I still get the same behaviour after installing (and loading) Debugger. 
Yes, in a fresh new Julia environment I confirm, that I get the same behaviour after installing (and loading) Debugger.
I filed https://github.com/julia-vscode/julia-vscode/issues/1667

**Comment by mcabbott** [comment] 2021-04-26 17:12
Closing this as it looks like it's being tracked, and fixed, elsewhere.

**Closed by mcabbott** 2021-04-26 17:12 UTC
